version: "3.8"

networks:
  default:
    external:
      name: ${NETWORK_NAME}
    
services: 
  app:
    image: thielserra/ubuntu2204-apache-php71:v2
    tty: true
    container_name: ${SIA_CONTAINER_NAME}
    entrypoint: sh /docker-entrypoint.sh 
    restart: "always"
    volumes:
      - "../:/var/www/html"
      - "./apache/sites-available:/etc/apache2/sites-available"
      - "./apache/logs:/var/log/apache2"
    labels:
      - "traefik.http.routers.${SIA_CONTAINER_NAME}.rule=Host(`${SIA_CONTAINER_NAME}.docker.localhost`)"
    networks:
      - default
